### ISSUE TITLE
ImportError: cannot import name 'bbtools' from 'biotools' 

### ISSUE THREAD

**Issue by mattbird567** [lowandrew/FastQMixer#1]
Hi! 

I'm keen to use your tool to generate some synthtic reads that are contaminated but am aware that this project hasn't been updated in some time. I have run into the issue that bbtools cannot be found in biotools. Not sure if you know a quick fix for this. No worries if this project isn't being maintained anymore, just thought i would ask on the chance you might no how to fix it :) 

The issue:

`(env)  matt@PC1:~/FastQMixer$ python3 simulate_and_mix.py -h
Traceback (most recent call last):
  File "/home/matt/FastQMixer/simulate_and_mix.py", line 5, in <module>
    import fastqmixer
  File "/home/matt/FastQMixer/fastqmixer.py", line 4, in <module>
    from biotools import bbtools
ImportError: cannot import name 'bbtools' from 'biotools' (/home/matt/FastQMixer/env/lib/python3.9/site-packages/biotools/__init__.py)`

Best, 
Matt

**Comment by mattbird567** [comment]
I resolved the Isuues with the following:

pip install OLCTools == 0.3.45
pip install biopython == 1.7
sudo apt install art-nextgen-simulation-tools

This should meet all the requirements for the script to run.
